# Import Libaries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('default',category=DeprecationWarning)

# Read and Load dataset

In [2]:
dataset=pd.read_csv("Churn_Modelling.csv")
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

# check dataset info,describes,columns,shape,values isnull or not

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
dataset.describe().T

count          mean           std          min  \
RowNumber        10000.0  5.000500e+03   2886.895680         1.00   
CustomerId       10000.0  1.569094e+07  71936.186123  15565701.00   
CreditScore      10000.0  6.505288e+02     96.653299       350.00   
Age              10000.0  3.892180e+01     10.487806        18.00   
Tenure           10000.0  5.012800e+00      2.892174         0.00   
Balance          10000.0  7.648589e+04  62397.405202         0.00   
NumOfProducts    10000.0  1.530200e+00      0.581654         1.00   
HasCrCard        10000.0  7.055000e-01      0.455840         0.00   
IsActiveMember   10000.0  5.151000e-01      0.499797         0.00   
EstimatedSalary  10000.0  1.000902e+05  57510.492818        11.58   
Exited           10000.0  2.037000e-01      0.402769         0.00   

                         25%           50%           75%          max  
RowNumber            2500.75  5.000500e+03  7.500250e+03     10000.00  
CustomerId       15628528.25  1.569074e+07  1.575323e+07  15815690.00  
CreditScore           584.00  6.520000e+02  7.180000e+02       850.00  
Age                    32.00  3.700000e+01  4.400000e+01        92.00  
Tenure                  3.00  5.000000e+00  7.000000e+00        10.00  
Balance                 0.00  9.719854e+04  1.276442e+05    250898.09  
NumOfProducts           1.00  1.000000e+00  2.000000e+00         4.00  
HasCrCard               0.00  1.000000e+00  1.000000e+00         1.00  
IsActiveMember          0.00  1.000000e+00  1.000000e+00         1.00  
EstimatedSalary     51002.11  1.001939e+05  1.493882e+05    199992.48  
Exited                  0.00  0.000000e+00  0.000000e+00         1.00

In [5]:
dataset.shape

(10000, 14)

In [6]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [7]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

# Spliting the dataset into training and test dataset

In [8]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(dataset,test_size=0.2)

In [9]:
# saving test data into csv file
test.to_csv('test_file.csv',index=False,encoding='utf-8')

In [10]:
# split train data into train and cross validation dataset
train_data,cross_data = train_test_split(train,test_size=0.2,random_state=0)

In [11]:
train_data.shape,cross_data.shape

((6400, 14), (1600, 14))

# Separte dataset into Features and Labels

In [12]:
x_train=train_data.iloc[:,3:13].values
print(x_train.shape)
y_train=train_data.iloc[:,13].values
print(y_train.shape)

(6400, 10)
(6400,)


# Feature scaling

In [13]:
def categorial_encoding(x):
    from sklearn.preprocessing import LabelEncoder,OneHotEncoder
    labelencoder_X_1=LabelEncoder()
    x[:,1]=labelencoder_X_1.fit_transform(x[:,1])
    print(x.shape)
    labelencoder_X_2=LabelEncoder()
    x[:,2]=labelencoder_X_2.fit_transform(x[:,2])
    print(x.shape)
    onehotencoder=OneHotEncoder(categorical_features=[1])
    x=onehotencoder.fit_transform(x).toarray()
    print(x.shape)
    x=x[:,1:]
    return x

x_train=categorial_encoding(x_train)

(6400, 10)
(6400, 10)
(6400, 12)


/home/user/my_env/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/user/my_env/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [14]:
# seperating features and labels from dataset of cross validation dataset
# Credit Score through Estimated Salary
x_cv = cross_data.iloc[:,3:13].values
# Exited
y_cv = cross_data.iloc[:,13].values

In [15]:
x_cv=categorial_encoding(x_cv)

(1600, 10)
(1600, 10)
(1600, 12)


/home/user/my_env/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/user/my_env/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [16]:
# from sklearn.preprocessing import StandardScaler
# sc=StandardScaler()
# x_train=sc.fit_transform(x_train)
# x_cv=sc.transform(x_cv)

In [17]:
x_train.shape,y_train.shape,x_cv.shape,y_cv.shape

((6400, 11), (6400,), (1600, 11), (1600,))

In [18]:
!pip install xgboost

You should consider upgrading via the 'pip install --upgrade pip' command.


# Importing the Xgboost libaries fitting the training model

In [19]:
from xgboost import XGBClassifier
classifier=XGBClassifier()
classifier.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

# predict value

In [20]:
y_pred=classifier.predict(x_train)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [21]:
df = pd.DataFrame({'Actual': y_train, 'Predicted': y_pred})  
df.head()

Actual  Predicted
0       0          0
1       0          0
2       0          0
3       0          0
4       0          0

In [22]:
y_pred_cv=classifier.predict(x_cv)
x_cv

array([[0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 3.8794570e+04],
       [0.0000000e+00, 0.0000000e+00, 7.8600000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 6.6977680e+04],
       [0.0000000e+00, 0.0000000e+00, 8.2300000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2179200e+03],
       ...,
       [0.0000000e+00, 0.0000000e+00, 5.1600000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 3.3266290e+04],
       [1.0000000e+00, 0.0000000e+00, 6.7400000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.7570940e+05],
       [1.0000000e+00, 0.0000000e+00, 6.7800000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.3512396e+05]])

In [23]:
df = pd.DataFrame({'Actual': y_cv, 'Predicted': y_pred_cv})  
df.head()

Actual  Predicted
0       0          0
1       0          0
2       0          0
3       0          0
4       1          1

# make confision matrix

In [24]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred,y_train)
cm

array([[4959,  650],
       [ 148,  643]])

In [25]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred_cv,y_cv)
cm

array([[1215,  184],
       [  45,  156]])

# Apply k-fold cross_validation

In [26]:
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier, X = x_train,y = y_train,cv=10)
accuracies

array([0.85179407, 0.85647426, 0.87363495, 0.86875   , 0.859375  ,
       0.8703125 , 0.86875   , 0.87793427, 0.86071987, 0.88106416])

In [27]:
accuracies.mean()

0.8668809085990199

In [28]:
accuracies.std()

0.009043944875069303

In [29]:
import pickle
fileobject=open('test.pkl','wb')
pickle.dump(classifier,fileobject)
fileobject.close()