In [463]:
import pandas as pd
import seaborn as sb
import numpy as np
import warnings
warnings.simplefilter("ignore")
import sklearn.metrics
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.preprocessing import Imputer
from sklearn.linear_model import LogisticRegression
import importlib.util
from sklearn.metrics import confusion_matrix
from collections import defaultdict

In [464]:
dataset=pd.read_csv("test.csv", delimiter=",")
dataset.head()

A  B  C  D  E  F  G  H  Result
0  S  D  T  Y  Y  A  D  S       1
1  P  N  V  S  L  A  M  T       1
2  H  L  R  E  Y  Q  D  L      -1
3  Q  G  N  F  L  Q  S  R       1
4  S  T  D  Y  G  I  L  Q      -1

In [465]:
dataset.shape

(325, 9)

In [466]:
dataset.columns

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'Result'], dtype='object')

In [467]:
dataset.describe().T

count      mean       std  min  25%  50%  75%  max
Result  325.0 -0.556923  0.831845 -1.0 -1.0 -1.0 -1.0  1.0

In [468]:
dataset.sample()

A  B  C  D  E  F  G  H  Result
298  T  K  V  F  V  V  Q  P       1

In [469]:
dataset.isnull().sum()

A         0
B         0
C         0
D         0
E         0
F         0
G         0
H         0
Result    0
dtype: int64

In [470]:
import pickle
fileobject=open("training.pkl","rb")
classifier=pickle.load(fileobject)
sc=pickle.load(fileobject)

In [471]:
x_test=dataset.iloc[:,:-1].values
y_test=dataset.iloc[:,8].values


In [472]:
x_test.shape,y_test.shape

((325, 8), (325,))

In [473]:
x_test=pd.DataFrame(x_test)

In [474]:
type(x_test)

pandas.core.frame.DataFrame

In [475]:
 # from collections import defaultdict
d = defaultdict(LabelEncoder)
# Encoding the variable
fit = x_test.apply(lambda x: d[x.name].fit_transform(x))
# Inverse the encoded
fit.apply(lambda x: d[x.name].inverse_transform(x))
# Using the dictionary to label future data
x_test.apply(lambda x: d[x.name].transform(x))
one_hot_encode = OneHotEncoder()
one_hot_encode.fit(x_test)
x_test=one_hot_encode.transform(x_test).toarray()
print(x_test)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [476]:
#Encoding the dependent variable
labelencoder_y=LabelEncoder()
# print(labelencoder_y)
y_test=labelencoder_y.fit_transform(y_test)
# print(y_test)


In [477]:
#feature scaling
x_test=sc.transform(x_test)

In [478]:
#predicting the train set result
y_pred=classifier.predict(x_test)
dataset=pd.DataFrame({'Actual':y_test,'Predicted':y_pred})
print(dataset.head())

   Actual  Predicted
0       1          1
1       1          1
2       0          0
3       1          1
4       0          1


In [479]:
#making the confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[237  16]
 [  7  65]]


In [480]:
#check accuracy for X train data
Acc_test=sklearn.metrics.precision_score(y_pred,y_test)*100
print(Acc_test)

90.27777777777779
